### ISSUE TITLE
Transition to V4 endpoints

### ISSUE THREAD

**Issue by raitono** [raitono/LoLPA#4]
[Riot article](https://www.riotgames.com/en/DevRel/player-universally-unique-identifiers-and-a-new-security-layer)

I will need to wait for Kayn to get the new endpoints in place. I can then add the PUUIDs to the database. As another user mentioned, this will mean using the summonerName to lookup the PUUIDs as the account and summoner IDs are going to be encrypted.

Another thing to note is that PUUIDs are only unique per region. If a player changes region, the PUUID will follow them and exist in both regions, but their account and summoner IDs will be regenerated.

**Comment by raitono** [comment]
Oh, sorry @cnguy. Didn't realize GitHub would ping you just because I dropped the link to your issue here.

**Comment by cnguy** [comment]
don't worry about it! I did that before to some huge library (20k stars) by accident too; it's no big deal. If anything it just strengthens an issue
